export class ActionTypes {
	static USER_CLASSES = 'USER_CLASSES';
	static MANAGE_USERS = 'MANAGE_USERS';
	static CLASSES = 'CLASSES';
	static CATEGORY = 'CATEGORY';
	static STATISTIC = 'STATISTIC';

	static EDIT_ASSIGNMENT = 'EDIT_ASSIGNMENT';

	static USER_FEEDBACK_ASSIGNMENT = 'USER_FEEDBACK_ASSIGNMENT';
	static ASSIGNMENT = 'ASSIGNMENT';
	static USER_ERROR = 'USER_ERROR';
	static ASSIGNMENT_ACTIVITY = 'ASSIGNMENT_ACTIVITY';
	static ASSIGNMENT_TOPIC = 'ASSIGNMENT_TOPIC';
	static TEACHERS_CLASSES = 'TEACHERS_CLASSES';
	static TOPIC_TREE = 'TOPIC_TREE';
	static TEACHERS = 'TEACHERS';
	static STUDENTS = 'STUDENTS';
	static SEARCH = 'SEARCH';
	static SUCCESS = 'SUCCESS';
	static SAVE_DONE = 'SAVE_DONE';
	static FAILURE = 'FAILURE';
	static LOADING = 'LOADING';
	static UPDATE = 'UPDATE';
	static INSERT = 'INSERT';
	static DELETE = 'DELETE';
	static RESET = 'RESET';
	static RESET_SAVE = 'RESET_SAVE';
	static CREATE_SUCCESS = 'CREATE_SUCCESS';
	static SHOW_OR_HIDDEN_DIALOG = 'SHOW_OR_HIDDEN_DIALOG';
	static SHOW_UPDATE_CLASSES_DIALOG = 'SHOW_UPDATE_CLASSES_DIALOG';
	static LOAD_USER_CLASSES_BY_USERID = 'LOAD_USER_CLASSES_BY_USERID';
	static USER_ASSIGNMENT = 'USER_ASSIGNMENT';
	static USER_ASSIGNMENT_DETAIL = 'USER_ASSIGNMENT_DETAIL';
	static LOAD_USER_ASSIGNMENT_BY_USERID = 'LOAD_USER_ASSIGNMENT_BY_USERID';
	static UPDATE_USER_ASSIGNMENT = 'UPDATE_USER_ASSIGNMENT';
	static UPDATE_USER_ASSIGNMENT_REALTIME = 'UPDATE_USER_ASSIGNMENT_REALTIME';
	static LOAD_ASSIGNMENT_STATISTIC_BY_IDS = 'LOAD_ASSIGNMENT_STATISTIC_BY_IDS';
	static LOAD_ASSIGNMENT_STATISTIC_BY_IDS_SUCCESS = 'LOAD_ASSIGNMENT_STATISTIC_BY_IDS_SUCCESS';


	static LOAD_USER_ASSIGNMENT_BY_STATUS = 'LOAD_USER_ASSIGNMENT_BY_STATUS';
	static LOAD_USER_ASSIGNMENT_BY_ID = 'LOAD_USER_ASSIGNMENT_BY_ID';

	static LOAD_USER_ASSIGNMENT_BY_ASSID = 'LOAD_USER_ASSIGNMENT_BY_ASSID';
	static LOAD_USER_ASSIGNMENT_BY_ASSID_SUCCESS = 'LOAD_USER_ASSIGNMENT_BY_ASSID_SUCCESS';
	static LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES';

	static LOAD_ASSIGNMENT_TOPIC = 'LOAD_ASSIGNMENT_TOPIC';
	static LOAD_TOPIC_BY_COURSEIDS = 'LOAD_TOPIC_BY_COURSEIDS';
	static LOAD_TOPIC_TREE_DATA = 'LOAD_TOPIC_TREE_DATA';
	static LOAD_ROOT_TREE_DATA = 'LOAD_ROOT_TREE_DATA';
	static UPDATE_SELECTED_TOPIC_ASSIGNMENT = 'UPDATE_SELECTED_TOPIC_ASSIGNMENT';

	static SAVE_CLASSES = 'SAVE_CLASSES';
	static JOIN_NEW_CLASSES = 'JOIN_NEW_CLASSES';

	static LOAD_CLASSES_BY_USER_ID = 'LOAD_CLASSES_BY_USER_ID';
	static LOAD_ASS_STATISTIC_BY_DATE = 'LOAD_ASS_STATISTIC_BY_DATE';

	static SHOW_EDIT_ASS_MODAL = 'SHOW_EDIT_ASS_MODAL';
	static CLOSE_EDIT_ASS_MODAL = 'CLOSE_EDIT_ASS_MODAL';

	static LOAD_TIMEONSITE_STATISTIC_BY_DATE = 'LOAD_TIMEONSITE_STATISTIC_BY_DATE';
	static LOAD_TIME_ONLINE_STATISTIC_BY_DATE = 'LOAD_TIME_ONLINE_STATISTIC_BY_DATE';
	static CREATE_NEW_USERS = 'CREATE_NEW_USERS';
	static ADD_USER_TO_CLASSES = 'ADD_USER_TO_CLASSES';
	static REMOVE_USER_FROM_CLASSES = 'REMOVE_USER_FROM_CLASSES';

	static LOAD_TEACHERS_IN_CLASSES = 'LOAD_TEACHERS_IN_CLASSES';
	static LOAD_STUDENTS_IN_CLASSES = 'LOAD_STUDENTS_IN_CLASSES';
	static UPDATE_CURRENT_CLASSES_ID = 'UPDATE_CURRENT_CLASSES_ID';
	static SEARCH_TEACHERS_BY_TEXT = 'SEARCH_TEACHERS_BY_TEXT';
	static SEARCH_STUDENTS_BY_TEXT = 'SEARCH_STUDENTS_BY_TEXT';
	static SEARCH_TEACHERS_OR_STUDENT_BY_TEXT = 'SEARCH_TEACHERS_OR_STUDENT_BY_TEXT';
	static SAVE_NEW_ASSIGNMENT = 'SAVE_NEW_ASSIGNMENT';
	static UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT';

	static LOAD_USER_FEEDBACK = 'LOAD_USER_FEEDBACK';
	static SAVE_USER_FEEDBACK_ASSIGNMENT = 'SAVE_USER_FEEDBACK_ASSIGNMENT';
	static LOAD_ASSIGNMENT_ACTIVITY = 'LOAD_ASSIGNMENT_ACTIVITY';

	static PARENTS_CLASSES = 'PARENTS_CLASSES';
	static LOAD_PARENTS_IN_CLASSES = 'LOAD_PARENTS_IN_CLASSES';
	static ADD_PARENT_TO_CLASSES = 'ADD_PARENT_TO_CLASSES';

	static NOTIFICATIONS = 'NOTIFICATIONS';
	static LOAD_NOTIFICATION_BY_TEACHERID = 'LOAD_NOTIFICATION_BY_TEACHERID';
	static GET_INFO = 'GET_INFO';
	static EVENTS = 'EVENTS';
	static LOAD_EVENTS_BY_TEACHERID = 'LOAD_EVENTS_BY_TEACHERID';
	static NOTIFICATIONS_EVENTS = 'NOTIFICATIONS_EVENTS';
	static RELOAD = 'RELOAD';
	static REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
	static REMOVE_EVENT = 'REMOVE_EVENT';

	static EXERCISES = 'EXERCISES';
	static LOAD_EXERCISES_IN_CLASS = 'LOAD_EXERCISES_IN_CLASS';
	static DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';
	static COMBO_CLASS = 'COMBO_CLASS';
	static COMBO_REQUEST = 'COMBO_REQUEST';
	static UPDATE_COMBO_REQUEST = 'UPDATE_COMBO_REQUEST';
	static LOAD_COMBO_CLASS = 'LOAD_COMBO_CLASS';
	static REMOVE_COMBO_CLASS = 'REMOVE_COMBO_CLASS';
	static CREATE_NEW_COMBO_CLASS = 'CREATE_NEW_COMBO_CLASS';
}
